name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:

  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v3
    - name: Remove image,container
      run: docker rm -f nft_sender && docker rmi -f crawler_image
      continue-on-error: true
    - name: Build image
      run: docker build -t crawler_image .
    - name: Run container
      run: docker run -d --name nft_sender --restart=always crawler_image
      
